site_name: Web Labels Shopware Plugins
site_url: https://yourusername.github.io
site_description: Dokumentation für Web Labels Shopware Plugins

theme:
  name: material
  language: de
  logo: assets/logo.png
  favicon: assets/favicon.png
  palette:
    - scheme: default
      primary: white
      accent: white
      toggle:
        icon: material/brightness-7
        name: Dunkelmodus aktivieren
    - scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/brightness-4
        name: Hellmodus aktivieren
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.copy

plugins:
  - search:
      lang:
        - de
        - en
  - i18n:
      docs_structure: folder
      fallback_to_default: true
      languages:
        - locale: de
          name: Deutsch
          default: true
          build: true
        - locale: en
          name: English
          build: true
  - awesome-pages

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Plugins:
      - Produktberater:
          - Übersicht: plugins/WebLa_Produktberater/index.md
          - Anleitung: plugins/WebLa_Produktberater/how_to.md
          - Verwendung:
              - Allgemein: plugins/WebLa_Produktberater/usage/usage.md
              - Fragen: plugins/WebLa_Produktberater/usage/questions.md
              - Antworten: plugins/WebLa_Produktberater/usage/answers.md
          - Konfiguration: plugins/WebLa_Produktberater/configuration/settings.md
          - Changelog: plugins/WebLa_Produktberater/changelog.md