site_name: Web Labels Shopware Plugins
site_url: https://docs.web-labels.de/
site_description: Dokumentation für Web Labels Shopware Plugins

theme:
  name: material
  custom_dir: overrides
  language: de
  logo: assets/logo.png
  favicon: assets/favicon.png
  palette:
    - scheme: default
      primary: white
      accent: white
      toggle:
        icon: material/brightness-7
        name: Dunkelmodus aktivieren
    - scheme: slate
      primary: black
      accent: black
      toggle:
        icon: material/brightness-4
        name: Hellmodus aktivieren
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.copy

plugins:
  - search:
      lang:
        - de
        - en
  - awesome-pages
  - optimize
  - privacy
  - macros:
      include_yaml:
        - data/plugins.yml
  - i18n:
      docs_structure: folder
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: de
          name: Deutsch
          default: true
          build: true
          site_name: Web Labels Shopware Plugins
        - locale: en
          name: English
          build: true
          site_name: Web Labels Shopware Plugins

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true

extra:
  generator: false
  social:
    - icon: fontawesome/solid/globe
      link: https://web-labels.de
      name: Web Labels Website
    - icon: fontawesome/solid/shop
      link: https://store.shopware.com/web-labels-webdesign-gmbh.html
      name: Shopware Store
    - icon: fontawesome/solid/scale-balanced
      link: https://web-labels.de/impressum
      name: Impressum
    - icon: fontawesome/solid/user-shield
      link: https://web-labels.de/datenschutz
      name: Datenschutz

copyright: "&copy; 2026 Web Labels Webdesign GmbH"

nav:
  - Home: index.md
  - Plugins:
      - Produktberater:
          - Übersicht: plugins/WebLa_Produktberater/index.md
          - Anleitung: plugins/WebLa_Produktberater/how_to.md
          - Verwendung:
              - Allgemein: plugins/WebLa_Produktberater/usage/usage.md
              - Fragen: plugins/WebLa_Produktberater/usage/questions.md
              - Antworten: plugins/WebLa_Produktberater/usage/answers.md
          - Konfiguration: plugins/WebLa_Produktberater/configuration/settings.md
          - Changelog: plugins/WebLa_Produktberater/changelog.md